version: '3.7'

services:
  app:
    image: quench/mathapp:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      REDIS_URL: redis:6379
    depends_on:
     - redis
    networks:
      - webnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  webnet:
    driver: overlay
    attachable: true
